//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox_Class_Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingSpeed {
            get {
                return ((int)(this["TypingSpeed"]));
            }
            set {
                this["TypingSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int BlitzImportSpeed {
            get {
                return ((int)(this["BlitzImportSpeed"]));
            }
            set {
                this["BlitzImportSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReverseImport {
            get {
                return ((bool)(this["ReverseImport"]));
            }
            set {
                this["ReverseImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int FlexiProImportSpeed {
            get {
                return ((int)(this["FlexiProImportSpeed"]));
            }
            set {
                this["FlexiProImportSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""Name"":""Default"",""Devices"":[""CGM4981COM"",""CGM4331COM"",""TG4482A"",""IPTVTCXI6HD"",""IPTVARXI6HD"",""SCXI11BEI"",""XE2SGROG1"",""XS010XQ"",""SCHB1AEW"",""SCHC2AEW"",""SCHC3AE0"",""SCXI11BEI-ENTOS"",""MR36HW"",""S5A134A"",""CM8200A"",""CODA5810"",""WNXB11ABR"", ""WNXL11BWL"", ""NOVA2002"", ""LDHD2AZW"", ""H74470BA00-00007"", ""FLZB1-ECO""],""CtrIDs"":[""8052"",""8067"",""8090"",""8091"",""8134"",""NB1"",""NF1""]}]")]
        public string ContractorData {
            get {
                return ((string)(this["ContractorData"]));
            }
            set {
                this["ContractorData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8052, 8067, 8090, 8091, 8134, NB1, NF1")]
        public string CtrOrder {
            get {
                return ((string)(this["CtrOrder"]));
            }
            set {
                this["CtrOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CGM4331COM+TG4482A, IPTVTCXI6HD+IPTVARXI6HD, XS010XQ+XS010XB+XS020XONT+XS505M")]
        public string GroupedDevices {
            get {
                return ((string)(this["GroupedDevices"]));
            }
            set {
                this["GroupedDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rogers")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("961, 1007")]
        public string FlexiproPixel {
            get {
                return ((string)(this["FlexiproPixel"]));
            }
            set {
                this["FlexiproPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 151")]
        public string WmsPixel {
            get {
                return ((string)(this["WmsPixel"]));
            }
            set {
                this["WmsPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PushFlexiProData {
            get {
                return ((bool)(this["PushFlexiProData"]));
            }
            set {
                this["PushFlexiProData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl + X")]
        public string WmsFailAutomation {
            get {
                return ((string)(this["WmsFailAutomation"]));
            }
            set {
                this["WmsFailAutomation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WmsImportSpeed {
            get {
                return ((int)(this["WmsImportSpeed"]));
            }
            set {
                this["WmsImportSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\BTAutomation\\\\barcodes.txt")]
        public string BartenderPath {
            get {
                return ((string)(this["BartenderPath"]));
            }
            set {
                this["BartenderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ExcelColumn {
            get {
                return ((int)(this["ExcelColumn"]));
            }
            set {
                this["ExcelColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CTRAutomation {
            get {
                return ((bool)(this["CTRAutomation"]));
            }
            set {
                this["CTRAutomation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int CTRImportSpeed {
            get {
                return ((int)(this["CTRImportSpeed"]));
            }
            set {
                this["CTRImportSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"B176, B315, NB00, NB02, NB03, NB04, NB05, NB06, NB07, NB08, NB09, Ne15, Ne23, Ne26, Ne74, NF03, NF04, NF21, NF23, NF24, NF26, NF27, NF34, NF35, NF36, NF38, NF41, NF44, NF45, NF56, NF69, Nm43, NN17, NN19, NN24, NN46, NN51, NN53, NN54, NN57, NN58, NN60, NN61, NN62, NN63, NN64, NN66, NN67, NN68, NN71, NN72, NN73, NN75, NN79, NN80, NS07, NS09, NS15, NS17, NS22, NS23, NS32, NS34, NS36, NS41, NS53, NS55, NS57, NS68, ns71, NS73, Ns77, NS83, NS84, NS85, NS86, NS90, NS91, NS92, NS93, NS94, NS98")]
        public string TechIds {
            get {
                return ((string)(this["TechIds"]));
            }
            set {
                this["TechIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CGM4981COM, CGM4331COM, IPTVARXI6HD, SCXI11BEI, XE2SGROG1, XS010XB, SCHB1AEW, SCH" +
            "C2AEW, SCHC3AE0, SCXI11BEI-ENTOS, WNXB11ABR, WNXL11BWL, NOVA2002, LDHD2AZW, H744" +
            "70BA00-00007, FLZB1-ECO")]
        public string TechDevices {
            get {
                return ((string)(this["TechDevices"]));
            }
            set {
                this["TechDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunTechAutomation {
            get {
                return ((bool)(this["RunTechAutomation"]));
            }
            set {
                this["RunTechAutomation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TechHeaderText {
            get {
                return ((string)(this["TechHeaderText"]));
            }
            set {
                this["TechHeaderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int TechNumDown {
            get {
                return ((int)(this["TechNumDown"]));
            }
            set {
                this["TechNumDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isFirstRun {
            get {
                return ((bool)(this["isFirstRun"]));
            }
            set {
                this["isFirstRun"] = value;
            }
        }
    }
}
