//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox_Class_Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingSpeed {
            get {
                return ((int)(this["TypingSpeed"]));
            }
            set {
                this["TypingSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BlitzImportSpeed {
            get {
                return ((int)(this["BlitzImportSpeed"]));
            }
            set {
                this["BlitzImportSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Josh")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReverseImport {
            get {
                return ((bool)(this["ReverseImport"]));
            }
            set {
                this["ReverseImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int FlexiProImportSpeed {
            get {
                return ((int)(this["FlexiProImportSpeed"]));
            }
            set {
                this["FlexiProImportSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""Name"":""Default"",""Devices"":[""CGM4981COM"",""CGM4331COM"",""TG4482A"",""IPTVTCXI6HD"",""IPTVARXI6HD"",""SCXI11BEI"",""XE2SGROG1"",""XS010XQ"",""SCHB1AEW"",""SCHC2AEW"",""SCHC3AE0"",""SCXI11BEI-ENTOS"",""MR36HW"",""S5A134A"",""CM8200A"",""CODA5810""],""CtrIDs"":[""8017"",""8037"",""8038"",""8041"",""8047"",""8080"",""8093"",""8052"",""8067"",""8090"",""8091"",""8134"",""NB1"",""NF1""]},{""Name"":""Frontier"",""Devices"":[""CGM4981COM"",""CGM4331COM"",""TG4482A"",""IPTVTCXI6HD"",""IPTVARXI6HD"",""SCXI11BEI"",""XE2SGROG1"",""XS010XQ"",""SCHB1AEW"",""SCHC2AEW"",""SCHC3AE0"",""SCXI11BEI-ENTOS""],""CtrIDs"":[""8975"",""8994""]},{""Name"":""FrontierCoda"",""Devices"":[""CGM4981COM"",""CGM4331COM"",""TG4482A"",""IPTVTCXI6HD"",""IPTVARXI6HD"",""SCXI11BEI"",""XE2SGROG1"",""XS010XQ"",""SCHB1AEW"",""SCHC2AEW"",""SCHC3AE0"",""SCXI11BEI-ENTOS"",""CODA5810""],""CtrIDs"":[""8997""]}]")]
        public string ContractorData {
            get {
                return ((string)(this["ContractorData"]));
            }
            set {
                this["ContractorData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8017, 8037, 8038, 8041, 8047, 8080, 8093, 8052, 8067, 8090, 8091, 8134, 8975, 899" +
            "4, 8997, NB1, NF1")]
        public string CtrOrder {
            get {
                return ((string)(this["CtrOrder"]));
            }
            set {
                this["CtrOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CGM4331COM+TG4482A, IPTVTCXI6HD+IPTVARXI6HD, XS010XQ+XS010XB+XS020XONT+XS505M")]
        public string GroupedDevices {
            get {
                return ((string)(this["GroupedDevices"]));
            }
            set {
                this["GroupedDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rogers")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("961, 1016")]
        public string FlexiproPixel {
            get {
                return ((string)(this["FlexiproPixel"]));
            }
            set {
                this["FlexiproPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 149")]
        public string WmsPixel {
            get {
                return ((string)(this["WmsPixel"]));
            }
            set {
                this["WmsPixel"] = value;
            }
        }
    }
}
